### ISSUE TITLE
VEP official docker image as a WDL step

### ISSUE THREAD

**Issue by pgroves** [ncsa/phyloflow#20]
The Broad version: 

https://dockstore.org/workflows/github.com/alexanderhsieh/annotate_variants/annotate_variants:master?tab=info

**Comment by pgroves** [comment]
@ChuanyiZ can you tell which version of the docker image you did your testing with?

List is here:
https://hub.docker.com/r/ensemblorg/ensembl-vep/tags?page=1&ordering=last_updated

**Comment by ChuanyiZ** [comment]
I tested on release_104.0
